include: package:zekfad_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    prefer_relative_imports: false
    diagnostic_describe_all_properties: false
    sort_pub_dependencies: false